# 服务端口号
server:
  port: 8080


#spring配置
spring:
  application:
    name: microservice-sdphttpServer-8080 # 对外暴露的服务名称

  datasource: # 数据库配置
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://rm-2ze5abt8956gek832o.mysql.rds.aliyuncs.com/vip_sdpdev?useUnicode=true&characterEncoding=utf8
    username: sdpbiroot
    password: Sdpbiroot6688
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lqbs.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true     #mybatis二级缓存

#log4j2
logging:
  config: classpath:log4j2.xml